from langchain.tools import tool
from ddgs import DDGS
from langchain_openai import ChatOpenAI
import os
import datetime
from dotenv import load_dotenv

# Load environment variables (like API keys) from a .env file.
# This is a best practice to keep sensitive data out of the source code.
load_dotenv()

# THEORY: The @tool decorator is crucial for LangChain/LangGraph.
# It converts a standard Python function into a "Tool" object with a specific schema.
# The agent uses the function's type hints (e.g., query: str) and the docstring 
# ("Search the web...") to understand exactly WHEN and HOW to use this tool during its reasoning loop.
@tool()
def web_search(query: str) -> str:
  """Search the web for real-time info. Best for news or facts."""
  # CONCEPT: Using DuckDuckGo Search (DDGS) because it requires no API key 
  # and provides quick web snippets, acting as the agent's connection to the outside world.
  results = DDGS().text(query, max_results=5)
  if not results:
    return "No results found."
  
  # FLOW: Format the results for better readability by the LLM.
  # LLMs process structured text much better. Providing clear labels like Title, 
  # Snippet, and URL helps the agent extract the exact facts it needs without getting confused.
  formatted_results = "\n".join(
      [f"Title: {r['title']}\nSnippet: {r['body']}\nURL: {r['href']}\n" for r in results])
  return formatted_results

@tool()
def write_to_file(content: str, filename: str) -> str:
  """Write content to a file."""
  # CONCEPT: We use "a" (append) mode. If the agent needs to write multiple times 
  # in a single task, it won't overwrite its previous work. 
  # UTF-8 encoding ensures special characters generated by the LLM are saved correctly.
  with open(filename, "a", encoding="utf-8") as f:
        f.write(f"{content}\n")
  return f"Successfully saved to {filename}"

# CONCEPT: Initialize the LLM for summarization once to improve efficiency.
# WHY SEPARATE?: Sometimes we want a specific configuration for a sub-task.
# For summarization, a lower temperature (0.3) makes the output more factual and less creative.
# We use a local Ollama instance ("base_url") ensuring privacy and zero API costs.
summarize_llm = ChatOpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama",
    model="llama3.1",
    temperature=0.3
)

@tool()
def summarise(text: str) -> str:
  """Summarize long text, such as data from a web search, into a concise summary."""
  # FLOW: This tool allows the agent to delegate sub-tasks (like reading a massive block of text).
  # This is a powerful concept: it prevents the main agent's context window from overflowing 
  # and keeps its "attention" focused on the high-level plan.
  response = summarize_llm.invoke(f"Please provide a concise summary of the following text:\n\n{text}")
  return str(response.content)

# We group all tools into a list. The agent engine imports this and binds it to the LLM,
# injecting these capabilities into the LLM's system prompt.
tools_list = [web_search, write_to_file, summarise]
